### PR TITLE
Added IMPORTANT to check the package name in class

### PR DESCRIPTION
**Pull request by jogonzal-rh**

### CODE REVIEW

**Comment by danieloh30** [comment]
Good point. But the whole import section is too redundant. Can you just highlight "package io.konveyor.demo.ordermanagement.config;" without the import classes and input macro?

**Comment by jogonzal-rh** [comment]
Re-edit IMPORTANT message deleteing package and only mention the name of the package

**Comment by danieloh30** [comment]
Use this one:

[.console-output]
[source,bash,subs="+attributes,macros+"]

**Comment by jogonzal-rh** [comment]
Changed!

**Pull request merged**
